version: '3'

services:
  api:
    build: .
    container_name: agenda-api
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - ~/.ssh:/home/node/.ssh
    networks:
      - kong-net

networks:
  kong-net:
    external: true
