### Listar usuário
GET http://localhost:3000/api/v1/usuario



### Exibir usuário
GET http://localhost:3000/api/v1/usuario/a9ca34d8-5901-4390-8b86-7c0c06e0a135



### Criar usuário
POST http://localhost:3000/api/v1/usuario
Content-Type: application/json

{
  "email": "teste@gmail.com",
  "senha": "Alan@123"
} 
  


### Alterar usuário
PATCH http://localhost:3000/api/v1/usuario/a9ca34d8-5901-4390-8b86-7c0c06e0a135
Content-Type: application/json

{
  "ativo": true
}



###  Deletar usuário
DELETE http://localhost:3000/api/v1/usuario/60ef7402-6d63-41a6-afbd-455207d0056c
