### Listar usuário
GET http://localhost:3000/api/v1/usuario



### Exibir usuário
GET http://localhost:3000/api/v1/usuario/1



### Criar usuário
POST http://localhost:3000/api/v1/usuario
Content-Type: application/json

{
  "email": "teste@gmails.com",
  "senha": "Alan@123"
} 
  


### Alterar usuário
PATCH http://localhost:3000/api/v1/usuario/1
Content-Type: application/json

{
  "ativo": false
}



###  Deletar usuário
DELETE http://localhost:3000/api/v1/usuario/2
