# Usuário ---------------------------------------------
### Listar usuário
GET http://localhost:3000/api/v1/usuario

### Exibir usuário
GET http://localhost:3000/api/v1/usuario/d84ec75f-5bb9-4a3e-8dba-4caa1711e4c0

### Criar usuário
POST http://localhost:3000/api/v1/usuario
Content-Type: application/json

{
  "email": "teste@gmail.com",
  "senha": "Alan@123"
} 
  
### Alterar usuário
PATCH http://localhost:3000/api/v1/usuario/d84ec75f-5bb9-4a3e-8dba-4caa1711e4c0
Content-Type: application/json

{
  "ativo": true
}

###  Deletar usuário
DELETE http://localhost:3000/api/v1/usuario/6514ca43-6f24-42b6-9159-584197189423

# Cliente ---------------------------------------------
# Profissional-----------------------------------------
